### PR TITLE
Fix trails

### LINKED ISSUE #39: Trails effect crash when "Number of Trails" slider is too high
- use this gif: https://www.animatedimages.org/img-animated-frog-image-0015-51498.htm (this gif has 4 frames)
- add `Trails` effects
- move the slider to 6 to 10 range (pick any value from that range)
- crash!

Seems like the `Trails` effect only  works for 0 to `number of frames + 1` value.

The issue seems be to these computation:

https://github.com/MikeyBurkman/partymoji/blob/38301f2f10242c6509a79e962a545460be5937f2/src/effects/trails.ts#L52-L53

`frameIdx` can be negative value 

- If gif has 4 frames
- If the loop is in the first frame, `i = 0`
- number of trails is 10, `n = 10`
- `const idx = i - n + 1;` evaluates to `0 - 10 + 1` so `idx = -9`
- `const frameIdx = idx >= 0 ? idx : image.frames.length + idx;` evaluates to `frameIdx = 4 + -9` = `frameIdx = -5`

### PR DESCRIPTION
**Pull request by MikeyBurkman**
Fixes https://github.com/MikeyBurkman/partymoji/issues/39

Tested with both a short animation (where trails are kinda pointless) and with an image with many frames.

### CODE REVIEW

File: src/effects/trails.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const trails = buildEffect({
     for (let i = 0; i < image.frames.length; i += 1) {
       const canvas = canvasUtil.createCanvas(image.dimensions);
       for (let n = numTrails; n > 0; n -= 1) {
-        const idx = i - n + 1;
+        const idx = Math.max(i - n + 1, 0);
         const frameIdx = idx >= 0 ? idx : image.frames.length + idx;
```
Comment (vafada) [inline src/effects/trails.ts:53]: this `idx >= 0` check seem redundant now since `idx` is always have `>=0`

Comment (vafada) [reply src/effects/trails.ts:53]: the ternary operator is redundant. Hopefully `idx` is never >= to array length
